name: flnotification
description: Flutter plugin for Notification, a cross-platform
  messaging solution that lets you reliably deliver messages on Android and iOS.
author: YangZhang <ssea.zh@gmail.com>
homepage: https://github.com/flutter/plugins/tree/master/packages/firebase_messaging
version: 1.0.0

flutter:
  plugin:
    androidPackage: com.yangio.plugins.messaging
    iosPrefix: FLT
    pluginClass: MessagingPlugin

dependencies:
  meta: ^1.0.4
  platform: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.3.0
  mockito: ^3.0.0
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
